### ISSUE TITLE
QGIS crash on QGIS Datacube Query open

### ISSUE THREAD

**Issue by jankovicgd** [opendatacube/datacube-qgis#6]
QGIS crashes when opening Data Cube Query with following output:

```
QGIS died on signal 11[New LWP 993]
[New LWP 994]
[New LWP 995]
[New LWP 996]
[New LWP 997]
[New LWP 998]
[New LWP 999]
[New LWP 1006]
[New LWP 1007]
[New LWP 1009]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f9de79696c2 in __GI___waitpid (pid=1030, stat_loc=0x7ffd0b5fa8ac, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
[Current thread is 1 (Thread 0x7f9deb535380 (LWP 990))]
#0  0x00007f9de79696c2 in __GI___waitpid (pid=1030, stat_loc=0x7ffd0b5fa8ac, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
        resultvar = 18446744073709551104
        sc_cancel_oldtype = 0
#1  0x000055c1df11545e in  ()
#2  0x00007f9de78c3f20 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f9de9cfcf33 in QgsProcessingAlgorithm::setProvider(QgsProcessingProvider*) () at /usr/lib/libqgis_core.so.3.2.3
#4  0x00007f9de9cfcfd9 in QgsProcessingAlgorithm::create(QMap<QString, QVariant> const&) const () at /usr/lib/libqgis_core.so.3.2.3
#5  0x00007f9d44c41db1 in  () at /usr/lib/python3/dist-packages/qgis/_core.so
#6  0x00007f9d8d4af4aa in _PyCFunction_FastCallDict () at /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#7  0x00007f9d8d5af823 in  () at /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#8  0x00007f9d8d449f3d in _PyEval_EvalFrameDefault () at /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#9  0x00007f9d8d5ade43 in  () at /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#10 0x00007f9d8d5af443 in _PyFunction_FastCallDict () at /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#11 0x00007f9d8d559ac1 in _PyObject_FastCallDict () at /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#12 0x00007f9d8d55a69d in _PyObject_Call_Prepend () at /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#13 0x00007f9d8d55a708 in PyObject_Call () at /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#14 0x00007f9d8cc31c30 in  () at /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so
#15 0x00007f9d8cc32108 in  () at /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so
#16 0x00007f9d8cc32390 in  () at /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so
#17 0x00007f9d8cc32d07 in  () at /usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-36m-x86_64-linux-gnu.so
#18 0x00007f9de84d0679 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007f9de9466bf5 in QAbstractItemView::doubleClicked(QModelIndex const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007f9de94d945b in QTreeView::mouseDoubleClickEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007f9d46264c13 in  () at /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so
#22 0x00007f9de925e94f in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007f9de92ff4be in QFrame::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007f9de9472b3b in QAbstractItemView::viewportEvent(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007f9de94db4dc in QTreeView::viewportEvent(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007f9d462665e3 in  () at /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so
#27 0x00007f9de84a168c in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007f9de921f805 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007f9de922764f in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007f9de9d7bfcb in QgsApplication::notify(QObject*, QEvent*) () at /usr/lib/libqgis_core.so.3.2.3
#31 0x00007f9de84a19a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007f9de9226622 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007f9de927914b in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007f9de927b7ba in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007f9de921f82c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007f9de92270f4 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007f9de9d7bfcb in QgsApplication::notify(QObject*, QEvent*) () at /usr/lib/libqgis_core.so.3.2.3
#38 0x00007f9de84a19a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#39 0x00007f9de8a636c0 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#40 0x00007f9de8a64ff5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#41 0x00007f9de8a3c2eb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#42 0x00007f9dc3bfc1c0 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#43 0x00007f9ddc40b287 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#44 0x00007f9ddc40b4c0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#45 0x00007f9ddc40b54c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#46 0x00007f9de84fa8ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#47 0x00007f9de849f9ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#48 0x00007f9de84a8a84 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#49 0x000055c1df111b52 in  ()
#50 0x00007f9de78a6b97 in __libc_start_main (main=0x55c1df10f740, argc=1, argv=0x7ffd0b5fd088, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd0b5fd078) at ../csu/libc-start.c:310
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 4518090875948255782, 94291159502400, 140724794282112, 0, 0, 7695195093662452262, 7641212746140895782}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7f9deb387733 <_dl_init+259>, 0x7f9deb3495b8}, data = {prev = 0x0, cleanup = 0x0, canceltype = -348621005}}}
        not_first_call = <optimized out>
#51 0x000055c1df114e6a in _start ()
gdb returned 0
```

I have installed datacube along with the plugin with pip3 since conda-forge doesn't currently contain `qgis=3` for linux for some reason.

Output from `pip3 freeze`:
```
affine==2.2.1
asn1crypto==0.24.0
attrs==18.2.0
Automat==0.6.0
beautifulsoup4==4.6.0
blinker==1.4
cachetools==2.1.0
certifi==2018.1.18
cftime==1.0.1
chardet==3.0.4
Click==7.0
click-plugins==1.0.4
cligj==0.5.0
cloud-init==18.3
cloudpickle==0.6.0
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.1.4
cycler==0.10.0
dask==0.19.4
datacube==1.6.1
decorator==4.1.2
distro-info==0.18
future==0.15.2
GDAL==2.2.3
html5lib==0.999999999
httplib2==0.9.2
hyperlink==17.3.1
idna==2.6
incremental==16.10.1
ipython-genutils==0.2.0
Jinja2==2.10
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
jupyter-core==4.4.0
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
lxml==4.2.1
MarkupSafe==1.0
matplotlib==2.1.1
nbformat==4.4.0
netCDF4==1.4.1
numpy==1.15.2
oauthlib==2.0.6
olefile==0.45.1
OWSLib==0.16.0
PAM==0.4.2
pandas==0.23.4
Pillow==5.1.0
plotly==2.2.3
prettytable==0.7.2
psycopg2==2.7.5
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycrypto==2.6.1
pycurl==7.43.0.1
Pygments==2.2.0
pygobject==3.26.1
PyJWT==1.5.3
pyOpenSSL==17.5.0
pyparsing==2.2.2
pyPEG2==2.15.2
pyproj==1.9.5.1
pyserial==3.4
python-apt==1.6.2
python-dateutil==2.7.3
python-debian==0.1.32
pytz==2018.5
pyxdg==0.25
PyYAML==3.13
rasterio==1.0.8
requests==2.18.4
requests-unixsocket==0.1.5
SecretStorage==2.3.1
service-identity==16.0.0
singledispatch==3.4.0.3
six==1.11.0
snuggs==1.4.2
SQLAlchemy==1.2.12
ssh-import-id==5.7
systemd-python==234
toolz==0.9.0
traitlets==4.3.2
Twisted==17.9.0
ufw==0.35
unattended-upgrades==0.1
urllib3==1.22
webencodings==0.5
xarray==0.10.9
zope.interface==4.3.2
```

**Comment by lpinner** [comment]
Sorry for the delayed reply, I haven't been actively working on this project for a while.  However, now that conda-forge are packaging QGIS3 I've picked it up again.  It seems to be working fine using conda-forge QGIS 3.6.3.
